In [33]:

import os
import h5py
import sys
import numpy as np
import matplotlib
from PIL import Image
import pickle

In [30]:
path_train = '/Users/psangha/Desktop/Deep-Learning---Neural-Network-Design/all/train'

In [116]:
path_test = '/Users/psangha/Desktop/Deep-Learning---Neural-Network-Design/all/test1'

In [ ]:
path_example = '/Users/psangha/Desktop/Deep-Learning---Neural-Network-Design/all/train/cat.0.jpg'

* The shape of each image is (R,C,3) 
* Thus there are R rows C columns each with 3 RBG pixels

In [120]:
### Preprocessing 

def load_training_data(file_path,label1):
    labels = []
    X_flatten = []
    for file in os.listdir(file_path):
        image = Image.open(os.path.join(file_path,file))
        image_resize = image.resize((200, 200), Image.ANTIALIAS)
        array = np.asarray(image_resize)
        array = array.swapaxes(1,2).swapaxes(1,0)
        image.close()
        array_new = array.flatten()
        X_flatten.append(array_new)
        if file.startswith(label1):
            labels.append(0)
        else:
            labels.append(1)
    return np.array(X_flatten),labels

def load_test_data(file_path):
    X_flatten = []
    for file in os.listdir(file_path):
        image = Image.open(os.path.join(file_path,file))
        image_resize = image.resize((200, 200), Image.ANTIALIAS)
        array = np.asarray(image_resize)
        array = array.swapaxes(1,2).swapaxes(1,0)
        image.close()
        array_new = array.flatten()
        X_flatten.append(array_new)
    return np.array(X_flatten)
        

In [175]:
X_flatten, y_label = load_training_data(path_train,'cat')

In [101]:
X_flatten[1].shape

(120000,)

In [121]:
X_test_flatten = load_test_data(path_test)

In [42]:
class image_pre_process:
    
    def __init__(self,file_path, processing_type,bin_label0,bin_label1,iter_threshold = None):
        if processing_type!='training' and processing_type!='test':
            raise TypeError('processing_type must be training or test')
        self.file_path = file_path 
        self.iters = iter_threshold
        self.processing_type = processing_type
        self.label0 = bin_label0
        self.label1 = bin_label1
    
    def get_training_array(self):
        if self.iters:
            labels = []
            X_flatten = []
            label0_count = 0
            label1_count = 0
            
            for file in os.listdir(self.file_path):
                if file.startswith(self.label0) and label0_count<=self.iters:
                    image = Image.open(os.path.join(self.file_path,file))
                    image_resize = image.resize((200, 200), Image.ANTIALIAS)
                    array = np.asarray(image_resize)
                    array = array.swapaxes(1,2).swapaxes(1,0)
                    image.close()
                    array_new = array.flatten()
                    X_flatten.append(array_new)
                    labels.append(0)
                    label0_count +=1
                elif file.startswith(self.label1) and label1_count<=self.iters:
                    image = Image.open(os.path.join(self.file_path,file))
                    image_resize = image.resize((200, 200), Image.ANTIALIAS)
                    array = np.asarray(image_resize)
                    array = array.swapaxes(1,2).swapaxes(1,0)
                    image.close()
                    array_new = array.flatten()
                    X_flatten.append(array_new)
                    labels.append(1)
                    label1_count +=1
                    
                if label0_count == self.iters and label1_count ==self.iters:
                    break
            return np.array(X_flatten),labels
                    
        
            
            
            
    
    

In [43]:
a = image_pre_process(path_train,'training','cat','dog',iter_threshold = 10)
a.get_training_array()


(array([[ 25,  16,  22, ...,  78,  81,  84],
        [ 56,  46,  37, ...,  60,  64,  83],
        [ 86,  99, 100, ..., 111, 115, 118],
        ...,
        [199, 196, 201, ...,  75,  72,  71],
        [163, 166, 154, ..., 142, 134, 121],
        [ 22,  22,  22, ...,  27,  26,  26]], dtype=uint8),
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1])

### Test

In [142]:
x = np.array([   [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [145]:
x.shape

(2, 2, 3)

In [146]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [148]:
np.reshape(x,(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [149]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [164]:
x.swapaxes(1,2).swapaxes(1,0)

array([[[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]],

       [[ 3,  6],
        [ 9, 12]]])

In [159]:
y = np.array([[[1,4],[7,10]],[[2,5],[8,10]],[[3,6],[9,12]]])
y

array([[[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 10]],

       [[ 3,  6],
        [ 9, 12]]])

In [152]:
y.shape

(3, 2, 2)

In [155]:
x[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
x[0].shape

(2, 3)

In [158]:
x[0].flatten()

array([1, 2, 3, 4, 5, 6])

In [165]:
path_example = '/Users/psangha/Desktop/Deep-Learning---Neural-Network-Design/all/train/cat.0.jpg'

In [168]:
image = Image.open(path_example)
image_resize = image.resize((200, 200), Image.ANTIALIAS)

In [169]:
z = np.asarray(image_resize)

In [171]:
z.shape

(200, 200, 3)

In [172]:
z_swap = z.swapaxes(1,2).swapaxes(1,0)

In [174]:
z_swap.shape

(3, 200, 200)