# Vectorisation in Python

In [2]:
import numpy as np

* We can obtain $z = w^T*x+b$ by using np.dot in python

In [6]:
x = np.array([1,2,3,50,100])
y = np.array([3,4,5,10,47])
b = 10
z = np.dot(x,y)+b
print(z)

5236


## Speed up in time for vectorisation
* vectorisation exploits parallelisation in both GPU's and CPU's and as a result are a lot faster than for loops. 

In [15]:
import time 

# initialise two random vectors of dimension 1 million

a = np.random.rand(10000000)
b = np.random.rand(10000000)

# We start with the vectorised version
tic = time.time()

c = np.dot(a,b)

toc = time.time()

diff_vectorised = toc - tic

print('Vectorised version in milliseconds :'+str(diff_vectorised*1000)+'ms')

# Next we try the for loop

tic = time.time()

sum = 0
for index in range(1000000):
    sum += a[index]*b[index]

toc = time.time()

diff_looped = toc - tic

print('looped version in milliseconds :'+str(diff_looped*1000)+'ms')

print('The speed up by using vectorisation is '+str(1/(diff_vectorised/diff_looped))+ ' times')


Vectorised version in milliseconds :9.408950805664062ms
looped version in milliseconds :426.32484436035156ms
The speed up by using vectorisation is 45.31056152442732 times


In [17]:
v = np.array([2.7,100,2])
b = np.exp(v) # elementwise exponential operation
print(b)

[1.48797317e+01 2.68811714e+43 7.38905610e+00]


## Vectorising logistic regression forward pass 

* Recall we have $m$ training examples $(x_{1},y_{1}),\ldots,(x_{m},y_{m})$ with $x_{i} \in \mathbb{R}^{n_{x}}$
* For each example we compute $z_{i} = w^{T}x_{i}+b$ and then $a_{i} = \sigma(z_{i})$





In [50]:
# data

n_x = 10    # feature dimensionality
m = 3 # training sample size 
x1 = np.random.rand(n_x)
x2 = np.random.rand(n_x)
x3 = np.random.rand(n_x)
y1 = 0
y2 = 1
y3 = 0

y = np.array([y1,y2,y3])
w = np.array([100,2,3,5,10,200,30,1,6,8])   # weights vector

In [37]:
X = np.stack((x1,x2,x3),axis = -1)
print(X)

[[0.39732429 0.0879649  0.8744926 ]
 [0.8491405  0.88313677 0.6331414 ]
 [0.55149249 0.72980439 0.96729557]
 [0.05238606 0.97006001 0.00266972]
 [0.34761441 0.69797405 0.64967418]
 [0.58261928 0.22312668 0.95458838]
 [0.52374288 0.38721469 0.82597694]
 [0.93689477 0.07932701 0.41658208]
 [0.02695664 0.54463197 0.0602862 ]
 [0.16167373 0.43218378 0.66454221]]


In [39]:
z = np.dot(w.T,X)+10
z

array([191.45142765,  97.62858254, 329.91914098])

In [47]:
import math
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [49]:
# Equivalent to A = [z1,z2,z3]
# Since Z values are large a values will be near 1
A = sigmoid(z)
A

array([1., 1., 1.])

## Vectorising linear regression backward pass


Loss Function
* Recall we have $m$ training examples $(x_{1},y_{1}),\ldots,(x_{m},y_{m})$ with $x_{i} \in \mathbb{R}^{n_{x}}$
* For each example we compute $z_{i} = w^{T}x_{i}+b$ and then $a_{i} = \sigma(z_{i})$

* The loss function w.r.t one example say example $i$ is $L(a_{i},y_{i})=-y_{i}\mathrm{log}(a_{i})+(1-y_{i})\mathrm{log}(1-a_{i})$ where $a_{i} = \sigma(z_{i})$
* 'dai' is then $\frac{\partial L}{\partial a_{i}} = \frac{-y}{a_{i}}+\frac{1-y}{1-a_{i}}$
* 'dzi' is then $\frac{\partial L}{\partial z_{i}} = \frac{\partial L}{\partial a_{i}} \cdot \frac{\partial a_{i}}{\partial z_{i}} = a_{i}-y$
* 'dwi' is then $\frac{\partial L}{\partial w_{i}} = x_{i}dz_{i}$
* 'dbi' is then $\frac{\partial L}{\partial b_{i}} = dz_{i}$



Cost Function
* Now that we have a value for the loss w.r.t a single training example $1 \leq i \leq m$. We average to get the cost function $$J(w,b) = \frac{1}{m} \sum_{i=1}^{m} L(a^{i},y)$$
* We can distribute the partial derivatives across the sum for any variable we are interested in as follows
$$ \frac{\partial J}{\partial w_{i}} = \frac{1}{m} \sum_{i=1}^{m} \frac{\partial}{\partial w_{i}} L(a_{i},y^{i}) $$
* In our example dz = [dz1,dz2,dz3] = [a1-y1,a2-y2,a3-y3] = A-y
* $db = \frac{1}{m} \sum_{i=1}^{m} dz_{i}$ and we can calculate this as db = 1/m * np.sum(dz) 
